/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './message-input.component.ngfactory';
import * as import2 from './message-input.component';
import * as import3 from './message.service';
import * as import4 from './message-list.component.ngfactory';
import * as import5 from './message-list.component';
import * as import6 from './messages.component';
const styles_MessagesComponent:any[] = ([] as any[]);
export const RenderType_MessagesComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_MessagesComponent,
  data: {}
}
);
export function View_MessagesComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n            '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-component',([] as any[]),(null as any),(null as any),(null as any),import1.View_MessageInputComponent_0,import1.RenderType_MessageInputComponent)),
    import0.ɵdid(114688,(null as any),0,import2.MessageInputComponent,[import3.MessageService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),0,'hr',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n            '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-message-list',([] as any[]),(null as any),(null as any),(null as any),import4.View_MessageListComponent_0,import4.RenderType_MessageListComponent)),
    import0.ɵdid(114688,(null as any),0,import5.MessageListComponent,[import3.MessageService],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(ck,v) => {
    ck(v,4,0);
    ck(v,12,0);
  },(null as any));
}
function View_MessagesComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-messages',([] as any[]),(null as any),(null as any),(null as any),View_MessagesComponent_0,RenderType_MessagesComponent)),
    import0.ɵdid(49152,(null as any),0,import6.MessagesComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const MessagesComponentNgFactory:import0.ComponentFactory<import6.MessagesComponent> = import0.ɵccf('app-messages',import6.MessagesComponent,View_MessagesComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvdGxlZS9Qcm9kRGV2L21lYW4vbWVhblN0YWNrL2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL3RsZWUvUHJvZERldi9tZWFuL21lYW5TdGFjay9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL3RsZWUvUHJvZERldi9tZWFuL21lYW5TdGFjay9hc3NldHMvYXBwL21lc3NhZ2VzL21lc3NhZ2VzLmNvbXBvbmVudC50cy5NZXNzYWdlc0NvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvdGxlZS9Qcm9kRGV2L21lYW4vbWVhblN0YWNrL2Fzc2V0cy9hcHAvbWVzc2FnZXMvbWVzc2FnZXMuY29tcG9uZW50LnRzLk1lc3NhZ2VzQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgICAgIDxhcHAtbWVzc2FnZS1jb21wb25lbnQ+PC9hcHAtbWVzc2FnZS1jb21wb25lbnQ+XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8aHI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgICAgIDxhcHAtbWVzc2FnZS1saXN0PjwvYXBwLW1lc3NhZ2UtbGlzdD5cbiAgICAgICAgPC9kaXY+XG4gICAgIiwiPGFwcC1tZXNzYWdlcz48L2FwcC1tZXNzYWdlcz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNRO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBaUI7SUFDYjtnQkFBQTtJQUErQztJQUM3QztJQUNOO0lBQUk7TUFDSjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQWlCO0lBQ2I7Z0JBQUE7SUFBcUM7SUFDbkM7OztJQUxGO0lBSUE7Ozs7O0lDTlo7Z0JBQUE7Ozs7In0=
